
exp_cfg:
  num_trials_per_method: 3
  methods: 
    # 1cloth-openloop:
    #   rosparams: [
    #     ['robot_app/policy', 'openloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', ''],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 1cloth-random-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'random'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # {
    #   'name': 'random-image',
    #   'robot_app/policy': 'random',
    #   'robot_app/motion_key': 'slide_lift',
    #   'robot_app/grasp_command': 'pinch'
    #   'app/classifier_type': 'image',
    # },
    # random-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'random'],
    #     ['robot_app/motion_key', 'circular'],
    #     ['robot_app/grasp_command', 'pinchmoverub'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '2cloth'],
    #   ]
    closedloop-tactile:
      rosparams: [
        ['robot_app/policy', 'closedloop'],
        ['robot_app/motion_key', 'circular'],
        ['robot_app/grasp_command', 'pinchmoverub'],
        ['app/classifier_type', 'tactile'],
        ['app/cloth_type', '2cloth'],
      ]
    # 1cloth-complex-closedloop-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'closedloop'],
    #     ['robot_app/motion_key', 'circular'],
    #     ['robot_app/grasp_command', 'pinchmoverub'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 2cloth-closedloop-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'closedloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '2cloth'],
    #   ]