robot_app:
  random: [0.239, 0.233]
  # openloop: [0.239, 0.235, 0.228]
  openloop: [0.237, 0.235, 0.228]
  # openloop_noise: 0.001 # for finetuning data collection only
  openloop_noise: 0.000 # for finetuning data collection only
  closedloop: [0.239, 0.239]

  # random: [0.244, 0.234]
  # openloop: [0.242, 0.236, 0.233]
  # openloop_noise: 0.000 # for finetuning data collection only
  # closedloop: [0.244, 0.244]
  # closedloop_noise: 0.000
  
  increment: 0.002

exp_cfg:
  num_trials_per_method: 10
  methods: 
    # 1cloth-openloop:
    #   rosparams: [
    #     ['robot_app/policy', 'openloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', ''],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 1cloth-random-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'random'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 1cloth-random-image:
    #   rosparams: [
    #     ['robot_app/policy', 'random'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'image'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 1cloth-closedloop-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'closedloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 1cloth-closedloop-image:
    #   rosparams: [
    #     ['robot_app/policy', 'closedloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'image'],
    #     ['app/cloth_type', '1cloth'],
    #   ]
    # 2cloth-openloop:
    #   rosparams: [
    #     ['robot_app/policy', 'openloop'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', ''],
    #     ['app/cloth_type', '2cloth'],
    #   ]
    # 2cloth-random-tactile:
    #   rosparams: [
    #     ['robot_app/policy', 'random'],
    #     ['robot_app/motion_key', 'slide_lift'],
    #     ['robot_app/grasp_command', 'pinch'],
    #     ['app/classifier_type', 'tactile'],
    #     ['app/cloth_type', '2cloth'],
    #   ]
    2cloth-closedloop-image:
      rosparams: [
        ['robot_app/policy', 'closedloop'],
        ['robot_app/motion_key', 'slide_lift'],
        ['robot_app/grasp_command', 'pinch'],
        ['app/classifier_type', 'image'],
        ['app/cloth_type', '2cloth'],
      ]
    2cloth-closedloop-tactile:
      rosparams: [
        ['robot_app/policy', 'closedloop'],
        ['robot_app/motion_key', 'slide_lift'],
        ['robot_app/grasp_command', 'pinch'],
        ['app/classifier_type', 'tactile'],
        ['app/cloth_type', '2cloth'],
      ]
