# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linear_actuator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15linear_actuator.proto\"-\n\x0clin_actuator\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tjoint_pos\x18\x02 \x03(\x02\x62\x06proto3')



_LIN_ACTUATOR = DESCRIPTOR.message_types_by_name['lin_actuator']
lin_actuator = _reflection.GeneratedProtocolMessageType('lin_actuator', (_message.Message,), {
  'DESCRIPTOR' : _LIN_ACTUATOR,
  '__module__' : 'linear_actuator_pb2'
  # @@protoc_insertion_point(class_scope:lin_actuator)
  })
_sym_db.RegisterMessage(lin_actuator)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIN_ACTUATOR._serialized_start=25
  _LIN_ACTUATOR._serialized_end=70
# @@protoc_insertion_point(module_scope)
